//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.2
//     from Assets/KineticCore/Resources/KineticCoreInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @KineticCoreInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @KineticCoreInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""KineticCoreInput"",
    ""maps"": [
        {
            ""name"": ""New"",
            ""id"": ""cc6b625d-4072-4fe5-9d14-997ad6c8286c"",
            ""actions"": [
                {
                    ""name"": ""Btn1"",
                    ""type"": ""Button"",
                    ""id"": ""f8086909-4718-47f6-9e4a-5276a78e50c0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Btn2"",
                    ""type"": ""Button"",
                    ""id"": ""43845ed7-fe6b-4f60-8f08-67a430a53c4d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Btn3"",
                    ""type"": ""Button"",
                    ""id"": ""3e3bd0d1-44f3-4840-bd63-7c167d2a51f6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle1"",
                    ""type"": ""Button"",
                    ""id"": ""d5be0a68-f21e-49d5-801f-06efe7ec54ca"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle2"",
                    ""type"": ""Button"",
                    ""id"": ""3bde7e36-33e5-49a5-a23a-511ecd5070d3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Toggle3"",
                    ""type"": ""Button"",
                    ""id"": ""69c7522b-22be-4952-afc4-25c7bd978a71"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Knob1"",
                    ""type"": ""Value"",
                    ""id"": ""459f3967-cebd-4e9f-97b2-80d326070d38"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bd70cacc-1da0-4772-8f9d-7bd6215c81f8"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa2ca600-9be4-4b53-8fee-f6bae3931ae9"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ce18214c-0d35-421c-a49f-e7cf1d3f0393"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad58d49e-14c3-4476-9e32-034650ef3bcf"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd7bfa9c-ba52-4c0c-a3cb-5bef6d6b5275"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65ac36f0-0399-4154-997d-5439bd00aba2"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f24de76b-d54d-4939-b78b-e63e962e13af"",
                    ""path"": ""1DAxis(whichSideWins=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Knob1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b713b784-6419-4fd1-9391-45b86c7c3720"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Knob1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""f726531d-48f0-43f2-92cc-3cf2abb8c3bf"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Knob1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Pc"",
            ""bindingGroup"": ""Pc"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // New
        m_New = asset.FindActionMap("New", throwIfNotFound: true);
        m_New_Btn1 = m_New.FindAction("Btn1", throwIfNotFound: true);
        m_New_Btn2 = m_New.FindAction("Btn2", throwIfNotFound: true);
        m_New_Btn3 = m_New.FindAction("Btn3", throwIfNotFound: true);
        m_New_Toggle1 = m_New.FindAction("Toggle1", throwIfNotFound: true);
        m_New_Toggle2 = m_New.FindAction("Toggle2", throwIfNotFound: true);
        m_New_Toggle3 = m_New.FindAction("Toggle3", throwIfNotFound: true);
        m_New_Knob1 = m_New.FindAction("Knob1", throwIfNotFound: true);
    }

    ~@KineticCoreInput()
    {
        Debug.Assert(!m_New.enabled, "This will cause a leak and performance issues, KineticCoreInput.New.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // New
    private readonly InputActionMap m_New;
    private List<INewActions> m_NewActionsCallbackInterfaces = new List<INewActions>();
    private readonly InputAction m_New_Btn1;
    private readonly InputAction m_New_Btn2;
    private readonly InputAction m_New_Btn3;
    private readonly InputAction m_New_Toggle1;
    private readonly InputAction m_New_Toggle2;
    private readonly InputAction m_New_Toggle3;
    private readonly InputAction m_New_Knob1;
    public struct NewActions
    {
        private @KineticCoreInput m_Wrapper;
        public NewActions(@KineticCoreInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Btn1 => m_Wrapper.m_New_Btn1;
        public InputAction @Btn2 => m_Wrapper.m_New_Btn2;
        public InputAction @Btn3 => m_Wrapper.m_New_Btn3;
        public InputAction @Toggle1 => m_Wrapper.m_New_Toggle1;
        public InputAction @Toggle2 => m_Wrapper.m_New_Toggle2;
        public InputAction @Toggle3 => m_Wrapper.m_New_Toggle3;
        public InputAction @Knob1 => m_Wrapper.m_New_Knob1;
        public InputActionMap Get() { return m_Wrapper.m_New; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(NewActions set) { return set.Get(); }
        public void AddCallbacks(INewActions instance)
        {
            if (instance == null || m_Wrapper.m_NewActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NewActionsCallbackInterfaces.Add(instance);
            @Btn1.started += instance.OnBtn1;
            @Btn1.performed += instance.OnBtn1;
            @Btn1.canceled += instance.OnBtn1;
            @Btn2.started += instance.OnBtn2;
            @Btn2.performed += instance.OnBtn2;
            @Btn2.canceled += instance.OnBtn2;
            @Btn3.started += instance.OnBtn3;
            @Btn3.performed += instance.OnBtn3;
            @Btn3.canceled += instance.OnBtn3;
            @Toggle1.started += instance.OnToggle1;
            @Toggle1.performed += instance.OnToggle1;
            @Toggle1.canceled += instance.OnToggle1;
            @Toggle2.started += instance.OnToggle2;
            @Toggle2.performed += instance.OnToggle2;
            @Toggle2.canceled += instance.OnToggle2;
            @Toggle3.started += instance.OnToggle3;
            @Toggle3.performed += instance.OnToggle3;
            @Toggle3.canceled += instance.OnToggle3;
            @Knob1.started += instance.OnKnob1;
            @Knob1.performed += instance.OnKnob1;
            @Knob1.canceled += instance.OnKnob1;
        }

        private void UnregisterCallbacks(INewActions instance)
        {
            @Btn1.started -= instance.OnBtn1;
            @Btn1.performed -= instance.OnBtn1;
            @Btn1.canceled -= instance.OnBtn1;
            @Btn2.started -= instance.OnBtn2;
            @Btn2.performed -= instance.OnBtn2;
            @Btn2.canceled -= instance.OnBtn2;
            @Btn3.started -= instance.OnBtn3;
            @Btn3.performed -= instance.OnBtn3;
            @Btn3.canceled -= instance.OnBtn3;
            @Toggle1.started -= instance.OnToggle1;
            @Toggle1.performed -= instance.OnToggle1;
            @Toggle1.canceled -= instance.OnToggle1;
            @Toggle2.started -= instance.OnToggle2;
            @Toggle2.performed -= instance.OnToggle2;
            @Toggle2.canceled -= instance.OnToggle2;
            @Toggle3.started -= instance.OnToggle3;
            @Toggle3.performed -= instance.OnToggle3;
            @Toggle3.canceled -= instance.OnToggle3;
            @Knob1.started -= instance.OnKnob1;
            @Knob1.performed -= instance.OnKnob1;
            @Knob1.canceled -= instance.OnKnob1;
        }

        public void RemoveCallbacks(INewActions instance)
        {
            if (m_Wrapper.m_NewActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(INewActions instance)
        {
            foreach (var item in m_Wrapper.m_NewActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NewActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public NewActions @New => new NewActions(this);
    private int m_PcSchemeIndex = -1;
    public InputControlScheme PcScheme
    {
        get
        {
            if (m_PcSchemeIndex == -1) m_PcSchemeIndex = asset.FindControlSchemeIndex("Pc");
            return asset.controlSchemes[m_PcSchemeIndex];
        }
    }
    public interface INewActions
    {
        void OnBtn1(InputAction.CallbackContext context);
        void OnBtn2(InputAction.CallbackContext context);
        void OnBtn3(InputAction.CallbackContext context);
        void OnToggle1(InputAction.CallbackContext context);
        void OnToggle2(InputAction.CallbackContext context);
        void OnToggle3(InputAction.CallbackContext context);
        void OnKnob1(InputAction.CallbackContext context);
    }
}
